# Generated by Django 4.2.4 on 2023-08-27 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_blogpost_customimage_tag_featuredpost_blogposttag_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='keywords',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
