# Generated by Django 4.2.4 on 2023-08-24 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0004_featuredpost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='featuredpost',
            name='category',
        ),
    ]
